# Generated by Django 2.1.7 on 2019-02-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_requester_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation(Optional)'),
        ),
    ]
