# Generated by Django 2.1.7 on 2019-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='session',
        ),
        migrations.AddField(
            model_name='hit',
            name='assignment_id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False, verbose_name='Assignment ID'),
            preserve_default=False,
        ),
    ]
