# Generated by Django 2.1.7 on 2019-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='workerID',
            field=models.CharField(default='haobo', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='workerID',
            field=models.CharField(default='haobo', max_length=32),
            preserve_default=False,
        ),
    ]
