# Generated by Django 2.1.7 on 2019-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190618_1529'),
    ]

    def checkNoQA(apps, schema_editor):
        Question = apps.get_model("users", "Question")
        Answer = apps.get_model("users", "Answer")
        db_alias = schema_editor.connection.alias
        if Question.objects.using(db_alias).count() + Answer.objects.using(db_alias).count() != 0:
            raise ValueError('Questions and answers exist in the database. This migration cannot take place ' +
                'unless the database is empty. Please save all questions and answers, clear the database, and ' +
                'try again.')

    def revert(apps, schema_editor):
        Question = apps.get_model("users", "Question")
        Answer = apps.get_model("users", "Answer")
        HIT = apps.get_model("users", "HIT")
        db_alias = schema_editor.connection.alias
        for q in Question.objects.using(db_alias).all():
            q.workerID = HIT.objects.filter(assignment_id=assignmentID).workerID
            q.save()
        for a in Answer.objects.using(db_alias).all():
            a.workerID = HIT.objects.filter(assignment_id=assignmentID).workerID
            a.save()

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assignmentID',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='assignmentID',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(checkNoQA, revert, elidable=True),
        migrations.RemoveField(
            model_name='answer',
            name='workerID',
        ),
        migrations.RemoveField(
            model_name='question',
            name='workerID',
        ),
    ]
