# Generated by Django 2.1.7 on 2019-07-03 00:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_workerID_to_assignID'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE users_question
            ALTER COLUMN "imageID"
            TYPE varchar(64)[]
            USING array["imageID"]::varchar(64)[];
            """,
            """
            ALTER TABLE users_question
            ALTER COLUMN "imageID"
            TYPE varchar(64)
            USING "imageID"[1]::varchar(64);
            """,
            [
                migrations.AlterField(
                    model_name='question',
                    name='imageID',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
                )
            ],
        ),
        migrations.AlterField(
            model_name='hit',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
