# Generated by Django 2.1.7 on 2019-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_question_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=3)),
                ('instruction', models.TextField()),
            ],
        ),
    ]
