# Generated by Django 2.1.7 on 2019-02-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190222_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zipfile',
            name='tb',
        ),
        migrations.DeleteModel(
            name='Requester',
        ),
        migrations.DeleteModel(
            name='Zipfile',
        ),
    ]
