# Generated by Django 2.1.7 on 2019-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190228_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='airplanes/')),
                ('label', models.ManyToManyField(related_name='labels', to='users.Label')),
            ],
        ),
    ]
