# Generated by Django 2.1.7 on 2019-08-10 22:02

from django.db import migrations, models
import django.db.models.deletion


firstAnswer = 0

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190723_1559'),
    ]

    def storeFirstAnswer(apps, schema_editor):
        Answer = apps.get_model("users", "Answer")
        global firstAnswer
        firstAnswer = Answer.objects.all()[0].id
    def getFirstAnswer():
        global firstAnswer
        return firstAnswer

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='word',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(storeFirstAnswer, migrations.RunPython.noop, elidable=True),
        migrations.AddField(
            model_name='attribute',
            name='answer',
            field=models.ForeignKey(default=getFirstAnswer, on_delete=django.db.models.deletion.CASCADE, to='users.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
