# Generated by Django 2.1.7 on 2019-08-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190723_1559'),
    ]

    def checkNoAttr(apps, schema_editor):
        Attribute = apps.get_model("users", "Attribute")
        db_alias = schema_editor.connection.alias
        if Attribute.objects.using(db_alias).count() != 0:
            raise ValueError('Attributes exist in the database. This migration cannot take place ' +
                'unless the database is empty. Please save all attributes, clear the database, and ' +
                'try again.')

    operations = [
        migrations.RunPython(checkNoAttr, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='attribute',
            name='word',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='answer',
            field=models.OneToOneField(default=0, limit_choices_to={'isFinal': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rephrased', serialize=False, to='users.Answer'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            state_operations=[
                migrations.AddField(
                    model_name='answer',
                    name='hit',
                    field=models.ForeignKey(db_column='assignmentID', default=0, on_delete=django.db.models.deletion.CASCADE, to='users.HIT'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='question',
                    name='hit',
                    field=models.ForeignKey(db_column='assignmentID', default=0, on_delete=django.db.models.deletion.CASCADE, to='users.HIT'),
                    preserve_default=False,
                ),
                migrations.RemoveField(
                    model_name='answer',
                    name='assignmentID',
                ),
                migrations.RemoveField(
                    model_name='question',
                    name='assignmentID',
                ),
            ], elidable=True
        )
    ]
