# Generated by Django 2.1.7 on 2019-03-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
