# Generated by Django 2.1.7 on 2019-08-22 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190810_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='imgset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='hit',
            field=models.ForeignKey(db_column='assignmentID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.HIT'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.Question'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='hit',
            field=models.ForeignKey(db_column='assignmentID', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.HIT'),
        ),
        migrations.AddField(
            model_name='answer',
            name='imgset',
            field=models.IntegerField(default=-1),
        ),
        migrations.RemoveField(
            model_name='question',
            name='skipCount',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
