# Generated by Django 2.1.7 on 2019-04-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190322_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase01_instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=50, null=True)),
                ('imglink', models.CharField(max_length=100, null=True)),
                ('order', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Phase01 Instruction',
            },
        ),
    ]
