# Generated by Django 2.2.10 on 2020-03-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190822_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='cluster',
            field=models.CharField(default='A', max_length=1, verbose_name='Cluster'),
            preserve_default=False,
        ),
    ]
