# Generated by Django 2.1.7 on 2019-04-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190322_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundsNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
