# Generated by Django 2.2.10 on 2020-03-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_imagemodel_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='frameID',
            field=models.IntegerField(default=0),
        ),
    ]
