# Generated by Django 2.1.7 on 2019-04-05 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190405_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='listArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrlist', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('phase', models.CharField(default='phase02', max_length=10)),
            ],
        ),
    ]
