# Generated by Django 2.2.10 on 2020-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200606_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50, verbose_name='Detected features')),
                ('count', models.IntegerField(verbose_name='Frequency count')),
                ('is_bias', models.BooleanField(default=False)),
            ],
        ),
    ]
