# Generated by Django 2.1.7 on 2019-04-05 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_listarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarray',
            name='attrlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
