# Generated by Django 2.1.7 on 2019-04-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190405_0125'),
        ('users', '0015_phase03_instruction'),
    ]

    operations = [
    ]
