# Generated by Django 2.1.7 on 2019-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190405_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='phase02', max_length=10)),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
    ]
