# Generated by Django 2.1.7 on 2019-04-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_phasebreak'),
        ('users', '0016_merge_20190412_0119'),
    ]

    operations = [
    ]
