# Generated by Django 2.1.7 on 2019-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notsamevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase01_instruction',
            name='instruction',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='phase02_instruction',
            name='instruction',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='phase03_instruction',
            name='instruction',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
