# Generated by Django 2.1.7 on 2019-05-17 19:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190416_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(unique=True, upload_to=users.models.ImageModel.get_upload_path, validators=[users.models.ImageModel.validate_file_extension], verbose_name='Image'),
        ),
    ]
