# Generated by Django 3.0.3 on 2020-02-13 22:03

import cmpUI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(unique=True, upload_to=cmpUI.models.ImageModel.get_upload_path, validators=[cmpUI.models.ImageModel.validate_file_extension], verbose_name='Image')),
            ],
            options={
                'ordering': ('img',),
            },
        ),
    ]
