# Generated by Django 2.1.7 on 2019-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_player_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('isTaboo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zipfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_upload', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taboo1', models.ManyToManyField(related_name='first_taboo', to='users.Label')),
                ('taboo2', models.ManyToManyField(related_name='second_taboo', to='users.Label')),
                ('taboo3', models.ManyToManyField(related_name='third_taboo', to='users.Label')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age(Optional'),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='PlayerProfile/'),
        ),
    ]
