# Generated by Django 2.1.7 on 2019-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190222_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='tb1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='zipfile',
            name='tb2',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='zipfile',
            name='tb3',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
