# Generated by Django 2.1.7 on 2019-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.FileField(upload_to='airplanes/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='users.Label'),
        ),
    ]
