# Generated by Django 2.1.7 on 2019-04-13 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20190412_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotSameVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
