# Generated by Django 2.1.7 on 2019-05-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190517_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='obj',
        ),
    ]
