# Generated by Django 2.1.7 on 2019-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_question_imageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='imageID',
            field=models.CharField(default='airplanes/image_0001.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=64),
        ),
    ]
