# Generated by Django 2.1.7 on 2019-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190522_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='imageID',
            field=models.CharField(default='airplanes/image_0001.jpg', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
